project:
  type: website
  output-dir: docs

website:
  title: "MEMORIAS MATH IA"
  description: "Notas y ejercicios de MATH + IA"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Inicio
    right:
      - icon: github
        href: https://github.com/iamlauraherrera/MEMORIAS-MATH-IA

format:
  html:
    toc: true
    number-sections: false
    smooth-scroll: true
    theme:
      light: cosmo
      dark: slate
    lang: es

# Ejecuta cada .qmd una vez y guarda resultados si no cambian
execute:
  freeze: auto   # evita re-ejecutar si el código no cambió
  echo: false
  warning: false
  message: false