project:
  type: website
  output-dir: docs   # <- necesario para GitHub Pages

website:
  title: "MEMORIAS MATH IA"
  description: "Notas y ejercicios de MATH + IA"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      # Agrega aquí otras páginas si las tienes, por ejemplo:
      # - href: temario.qmd
      #   text: Temario
      # - href: practicas.qmd
      #   text: Prácticas
    right:
      - icon: github
        href: https://github.com/iamlauraherrera/MEMORIAS-MATH-IA

format:
  html:
    toc: true
    number-sections: false
    smooth-scroll: true
    theme:
      light: cosmo
      dark: slate
    lang: es

# Opcional: configura cómo se renderiza cada .qmd por defecto
execute:
  echo: false
  warning: false
  message: false
