project:
  type: website
  output-dir: docs

website:
  title: "MEMORIAS MATH IA"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Inicio
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - complejos-potenciacion-radicacion.qmd
      - algebra-lineal.qmd
      - ecuaciones-en-diferencia.qmd
      - ecuaciones-diferenciales-finanzas.qmd
      - ecuaciones-logisticas.qmd
      - series-y-transformadas.qmd

format:
  html:
    theme:
      light: journal  
      dark: slate    
    math: katex       
    toc: true
    number-sections: false
    smooth-scroll: true
    lang: es

execute:
  freeze: auto