project:
  type: book
  output-dir: docs     # 👈 agrega esta línea

book:
  title: "Memorias de Matemáticas para la IA"
  author: "Laura Herrera"
  date: today
  chapters:
    - index.qmd
    - complejos-potenciacion-radicacion.qmd
    - algebra-lineal.qmd
    - ecuaciones-en-diferencia.qmd
    - ecuaciones-diferenciales-finanzas.qmd
    - ecuaciones-logisticas.qmd
    - series-y-transformadas.qmd

format:
  pdf:
    pdf-engine: lualatex
    toc: true
    number-sections: true
    keep-tex: false
    latex-clean: true
  html:
    number-sections: true
    css: cm-web.css
    html-math-method: katex   # fórmulas bonitas en navegador con tipografía TeX

execute:
  echo: true
  warning: false
  error: false