name: Publish Quarto Book to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2  # instala Quarto
        with:
          version: "stable"

      # Si usas R/Python, instala aquí dependencias

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2  # Render del proyecto

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site  # carpeta de salida por defecto

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
